Prevent NPEs when Ofile has no hasher
Integration tests were failing with NPEs:

```
InternalException: exception ::omero::InternalException
{
    serverStackTrace = java.lang.NullPointerException
    at ome.services.blitz.repo.RepositoryDaoImpl.fileContext(RepositoryDaoImpl.java:838)
    at ome.services.blitz.repo.RepositoryDaoImpl.getRawFileStore(RepositoryDaoImpl.java:144)
    at ome.services.blitz.repo.PublicRepositoryI.createRepoRFS(PublicRepositoryI.java:467)
    at ome.services.blitz.repo.PublicRepositoryI.file(PublicRepositoryI.java:370)
```
caused by an inner join on originalfile.hasher. Since
the field is nullable, this needs to be a left outer join.