Move algorithm lookup after null file check
NPEs were being thrown due to the getOriginalFile call
before checking the `FsFile` for nullness:

```
UnknownException: exception ::Ice::UnknownException
{
    unknown = java.lang.NullPointerException
    at ome.services.blitz.repo.PublicRepositoryI.checkId(PublicRepositoryI.java:676)
    at ome.services.blitz.repo.PublicRepositoryI.fileById(PublicRepositoryI.java:374)
```